app/ansible/forms.py
# coding: utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, InputRequired
from ..ansible_ext import get_inventory_group


class AddAnsibleForm(FlaskForm):
    group = SelectField('Group', coerce=str, validators=[DataRequired()])
    host = StringField('Host', validators=[DataRequired()])
    user = SelectField('User', coerce=str, validators=[DataRequired()])
    command = StringField('Command', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(AddAnsibleForm, self).__init__(*args, **kwargs)
        self.group.choices = [(0, 'Choose...')] + [(i, i) for i in get_inventory_group() if i != "all:vars" ] + [('all', 'all')]
        self.user.choices = [('apprun', 'apprun'), ('root', 'root')]

app/ansible/__init__.py
# coding: utf-8
from flask import Blueprint

ansible = Blueprint('ansible', __name__)

from . import views

app/ansible/views.py
# coding: utf-8
from flask import render_template, redirect, request, url_for, flash, jsonify, make_response
from flask_login import login_required, current_user
from . import ansible
from .forms import AddAnsibleForm
from .. import flash_errors
from config import Config
from .. import celery_runner
import os, json, urllib2, base64, time, re
from ..ansible_ext import get_ansible_inventory_hosts
from datetime import datetime


@ansible.route('/ansible-command')
@login_required
def ansible_command():
    add_deploy_form = AddAnsibleForm()
    return render_template('ansible/ansible_command.html', add_deploy_form=add_deploy_form)


@ansible.route('/ansible-command-add', methods=['POST'])
@login_required
def ansible_command_add():
    form = AddAnsibleForm(data=request.get_json())
    if form.validate_on_submit():
        group = form.group.data
        host = form.host.data
        user = form.user.data
        command = form.command.data
        if host == "all":
            exec_command = str.format("{0} {1} -u {2} -i {3} --private-key={4} -m shell -a \"{5}\"",
                                 Config.ANSIBLE_COMMAND, group, Config.ANSIBLE_USER, Config.ANSIBLE_INVENTORY_FILE,
                                 Config.ANSIBLE_KEY, command)
        else:
            exec_command = str.format("{0} {1} -u {2} -i {3} --private-key={4} -m shell -a \"{5}\"",
                                      Config.ANSIBLE_COMMAND, host, Config.ANSIBLE_USER, Config.ANSIBLE_INVENTORY_FILE,
                                      Config.ANSIBLE_KEY, command)
        if user == "root":
            exec_command = exec_command + " -b --become-user=root"
        print "ansible_command - " + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + " : " + exec_command
        task_result = celery_runner.ansible_running_task.apply_async([exec_command])
        result = {'r': 0, 'task_id': task_result.id, 'Location': url_for('.ansible_command_status', task_id=task_result.id)}
    else:
        result = {'r': 1, 'error': form.errors}
    return jsonify(result)


@ansible.route('/ansible-command-status/<string:task_id>')
@login_required
def ansible_command_status(task_id):
    task = celery_runner.ansible_running_task.AsyncResult(task_id)
    if task.state == 'PENDING':
        result = "Task not found"
        resp = make_response((result, 404))
        return resp
    if task.state == "PROGRESS":
        result_obj = {'Status': "PROGRESS",
                      'description': "Task is currently running",
                      'returncode': None}
    else:
        try:
            return_code = task.info['returncode']
            description = task.info['description']
            if return_code is 0:
                result_obj = {'Status': "SUCCESS",
                              'Out': task.info['output'].encode('utf-8').strip(),
                              'description': description,
                              'returncode': return_code}
            else:
                result_obj = {'Status': "FLANSIBLE_TASK_FAILURE",
                              'Out': task.info['output'].encode('utf-8').strip(),
                              'description': description,
                              'returncode': return_code}
        except:
            result_obj = {'Status': "CELERY_FAILURE"}

    return jsonify(result_obj)


@ansible.route('/ansible-command-history')
@login_required
def ansible_command_history():
    return render_template('ansible/ansible_command_history.html')


@ansible.route('/get-hosts')
@login_required
def get_hosts():
    group = request.args.get('group')
    if group:
        hosts = get_ansible_inventory_hosts(group)
        return jsonify(hosts)
    else:
        return jsonify({})


@ansible.route('/flower-list')
@login_required
def flower_list():
    task_id = request.args.get('task_id')
    if task_id:
        tasks_api = Config.FLOWER_URL + 'api/task/info/' + task_id
        request_url = urllib2.Request(tasks_api)
        base64string = base64.encodestring('%s:%s' % (Config.FLOWER_USER, Config.FLOWER_PASSWORD)).replace('\n', '')
        request_url.add_header("Authorization", "Basic %s" % base64string)
        response = urllib2.urlopen(request_url)
        data = str(response.read().decode('utf-8')).replace('\'', '"')
        results = json.loads(data)
        if results['name'] != 'app.celery_runner.ansible_running_task':
            results = {}
    else:
        tasks_api = Config.FLOWER_URL + 'api/tasks'
        request_url = urllib2.Request(tasks_api)
        base64string = base64.encodestring('%s:%s' % (Config.FLOWER_USER, Config.FLOWER_PASSWORD)).replace('\n', '')
        request_url.add_header("Authorization", "Basic %s" % base64string)
        response = urllib2.urlopen(request_url)
        data = response.read().decode('utf-8')
        values = json.loads(data)
        results = []
        for key, value in values.iteritems():
            if value['name'] != 'app.celery_runner.ansible_running_task':
                continue
            uuid = value['uuid']
            args = value['args'][3:-2]
            if value['result']:
                try:
                    result = json.loads(re.sub(r" \'([a-zA-Z]+)\' ",r" \1 ",str(value['result']))
                                    .replace('\', u', ', u').replace('u\'' , '').replace('\']', ']')
                                    .replace('`fi\'\\n', 'fi ').replace("don't", 'don^t').replace("'s ", '^s ')
                                    .replace('\': "', '\': \'').replace('", \'', '\', \'')
                                    .replace('\\\'', '').replace('\"', '^').replace('\'', '"')
                                    .replace('\\x1b', '').replace('\\n', '<br />').replace('\\', '')
                                    .replace('[1;31;40m', '<font color=red>').replace('[1;32;40m', '<font color=green>')
                                    .replace('[1;33;40m', '<font color=cyan>').replace('[1;34;40m', '<font color=blue>')
                                    .replace('[0m', '</font>'))
                except:
                    print "[ERROR] [json] task-id: " + str(value['uuid'])
                    result = ''
            else:
                result = ''
            timestamp = datetime.fromtimestamp(value['timestamp']).strftime('%Y-%m-%d %H:%M:%S')
            state = value['state']
            results.append({
                'uuid': uuid,
                'args': args,
                'group': args.split()[1],
                'command': args.split()[-1],
                'result': result,
                'timestamp': timestamp,
                'state': state
            })
    return jsonify(results)

app/templates/ansible/ansible_command.html
{% extends "base.html" %}

{% block title %}{{ config['SITE_NAME'] }} - Ansible Command{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Ansible Command</h2>
</div>

<div class="col-md-12">
    <form id="ansible_command_add" action="{{ url_for('ansible.ansible_command_add') }}" class="form-inline" method="POST">
        {{ add_deploy_form.csrf_token }}
        <div class="form-group">
            <label for="group">{{ add_deploy_form.group.label }}：</label>
            {{ add_deploy_form.group(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="host">{{ add_deploy_form.host.label }}：</label>
            <select class="form-control" id="host" name="host">
                <option value="0">Choose...</option>
            </select>
        </div>

        <div class="form-group">
            <label for="user">{{ add_deploy_form.user.label }}：</label>
            {{ add_deploy_form.user(class="form-control") }}
        </div>

        <div class="form-group">
            <label for="command">{{ add_deploy_form.command.label }}：</label>
            {{ add_deploy_form.command(class="form-control",size="50") }}
        </div>

        <button type="submit" class="btn btn-primary">submit</button>
    </form>
</div>

<div class="col-md-12">
    <hr />
</div>

<div class="col-md-12">
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <p id="result"></p>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
function start_deploy_task() {
    var url = "{{ url_for('ansible.ansible_command_add') }}";
    var csrf_token = $('#csrf_token').val();
    var group = $('#group').val();
    var host = $('#host').val();
    var user = $('#user').val();
    var command = $('#command').val();

    // send ajax POST request to start background job
    $.ajax({
        type: 'POST',
        data: {'csrf_token':csrf_token, 'group':group, 'host':host, 'user': user, 'command':command},
        url: url,
        success: function(data, status, request) {
            if (data['r']==0){
                status_url = data['Location'];
                console.log("status_url: " + status_url);
                update_progress(status_url);
            }else{
                alert(data['error']);
                console.log(data['error']);
            }
        },
        error: function() {
            alert('Unexpected error');
        }
    });
}

function update_progress(status_url) {
    // send GET request to status URL
    $.getJSON(status_url, function(data) {
        var group = $('#group').val();
        var host = $('#host').val();
        var command = $('#command').val();

        // update UI
        $(':input[type="submit"]').prop('disabled', true);
        $('#result').empty();
        $('#result').append("<img src=\"/static/images/loading.gif\" /><span class=\"text-warning\"><strong>" + group + "</strong> is Execing...</sparn>");
        console.log(data['Status']);
        if (data['Status'] != 'PENDING' && data['Status'] != 'PROGRESS') {
            html = "<p class=\"text-primary\">Group: <strong>" + group + "</strong></p>" +
                "<p class=\"text-primary\">Host: <strong>" + host + "</strong></p>" +
                "<p class=\"text-primary\">Command: <strong>" + command + "</strong></p>" +
                "<p class=\"bg-primary text-warning\">Result: </p>";
            //html = '';

            if (data['Status'] == 'SUCCESS') {
                // show result
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong>Ansible is ' + data['Status'] + '</strong></p><p>' + data['Out'].replace(/\n/g, '<br />') + '</p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
            }else if(data['Status'] == 'CELERY_FAILURE'){
                // something unexpected happened
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong><strong>Ansible is ' + data['Status'] +  '.</strong></p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
            } else {
                // something unexpected happened
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong>Ansible is ' + data['Status'] +  '</strong></p><p>' +  data['Out'].replace(/\n/g, '<br />') + '</p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
            }
        } else {
            // rerun in 2 seconds
            setTimeout(function() {
                update_progress(status_url);
            }, 2000);
        }
    });
}

$(function() {
    $('#group').change(function() {
        if($('#group').val() == 0){
            $("#host").empty();
            $("#host").append("<option value=\"0\">Choose...</option>");
            return false;
        }
        var url = "{{ url_for('ansible.get_hosts') }}?group=" + $('#group').val();
        $.get(url, function(result){
            $("#host").empty(); //clean select option
            $("#host").append("<option value=all>all</option>");
            for(var item in result){
                $("#host").append("<option value=" + result[item] + ">" + result[item] + "</option>");
            }
        });
    });

    $('#ansible_command_add').submit(function(event) {
        start_deploy_task();
        event.preventDefault();
    });
});
</script>
{% endblock %}

app/templates/ansible/ansible_command_history.html
{% extends "base.html" %}

{% block title %}{{ config['SITE_NAME'] }} - Ansible Command History{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap-table-1.11.1/bootstrap-table.min.css') }}">
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Ansible Command History</h2>
</div>

<table id="ListTable"
       data-toggle="table"
       data-url="{{ url_for('ansible.flower-list') }}"
       data-method	="get"
       data-query-params=""
       data-pagination="true"
       data-page-size=10
       data-page-list="[10, 25, 50, All]"
       data-search="true"
       data-sort-name="timestamp"
       data-sort-order="desc"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-columns="true"
       data-show-export="true"
       data-export-data-type="selected"
       data-show-pagination-switch="true"
       data-striped="true"
       data-toolbar="#toolbar">
    <thead>
        <tr>
            <th data-field="uuid" data-sortable="false" data-switchable="false" data-visible="false">UUID</th>
            <th data-field="group" data-sortable="true">group</th>
            <th data-field="command" data-sortable="false">command</th>
            <th data-field="timestamp" data-sortable="true">Time</th>
            <th data-field="state" data-sortable="false" data-visible="false">State</th>
            <th data-field="result.output" data-sortable="true">Result</th>
        </tr>
    </thead>
</table>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='bootstrap-table-1.11.1/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap-table-1.11.1/locale/bootstrap-table-zh-CN.min.js') }}"></script>
<script>
$(function () {
    $('#ListTable').bootstrapTable({
    });
});
</script>
{% endblock %}