app/deploy/forms.py
# coding: utf-8
from flask import current_app
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, InputRequired
from ..jenkins_ext import jobs_list_get


class AddDeployForm(FlaskForm):
    module = SelectField('Module', coerce=str, validators=[DataRequired()])
    deploy_dir = SelectMultipleField('Deploy_dir')
    version = StringField('Version', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(AddDeployForm, self).__init__(*args, **kwargs)
        self.module.choices = [(0, 'Choose...')] + [(i, i) for i in jobs_list_get()]


class JenkinsExecForm(FlaskForm):
    job_name = SelectField('Job', coerce=str, validators=[DataRequired()])
    tag = StringField('Tag')
    job_type = StringField('type')

    def __init__(self, *args, **kwargs):
        super(JenkinsExecForm, self).__init__(*args, **kwargs)
        self.job_name.choices = [(0, 'Choose...')] + [(i, i) for i in jobs_list_get()]

app/deploy/__init__.py
# coding: utf-8
from flask import Blueprint

deploy = Blueprint('deploy', __name__)

from . import views

app/deploy/views.py
# coding: utf-8
from flask import render_template, redirect, request, url_for, flash, jsonify, make_response
from flask_login import login_required, current_user
from . import deploy
from .. import flash_errors
from .forms import AddDeployForm, JenkinsExecForm
from ..jenkins_ext import job_get_number, job_build, job_get_svn, get_job_build_status, get_repo_info
from ..svn_ext import svn_tag_list
from ..gitlab_ext import gitlab_tag_list
from ..ansible_ext import get_inventory_hosts
from config import Config
from .. import celery_runner
import os, json, urllib2, base64, time
from datetime import datetime


@deploy.route('/deploy-module')
@login_required
def deploy_module():
    add_deploy_form = AddDeployForm()
    return render_template('deploy/deploy_module.html', add_deploy_form=add_deploy_form)


@deploy.route('/deploy-module-add', methods=['POST'])
@login_required
def deploy_module_add():
    form = AddDeployForm(data=request.get_json())
    if form.validate_on_submit():
        module = form.module.data
        version = form.version.data
        deploy_dir = ','.join(request.form.getlist("deploy_dir[]"))
        exec_script = Config.DEPLOY_SCRIPT
        command = str.format("{0} -m {1} -d {2} -v {3}", exec_script, module, deploy_dir, version)
        print "ansible_command - " + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()) + " : " + command
        task_result = celery_runner.deploy_running_task.apply_async([command])
        result = {'r': 0, 'task_id': task_result.id, 'Location': url_for('.deploy_module_status', task_id=task_result.id)}
    else:
        result = {'r': 1, 'error': form.errors}
    return jsonify(result)


@deploy.route('/deploy-module-status/<string:task_id>')
@login_required
def deploy_module_status(task_id):
    task = celery_runner.deploy_running_task.AsyncResult(task_id)
    if task.state == 'PENDING':
        result = "Task not found"
        resp = make_response((result, 404))
        return resp
    if task.state == "PROGRESS":
        result_obj = {'Status': "PROGRESS",
                      'description': "Task is currently running",
                      'returncode': None}
    else:
        try:
            return_code = task.info['returncode']
            description = task.info['description']
            if return_code is 0:
                result_obj = {'Status': "SUCCESS",
                              'Out': task.info['output'].encode('utf-8').strip(),
                              'description': description,
                              'returncode': return_code}
            else:
                result_obj = {'Status': "FLANSIBLE_TASK_FAILURE",
                              'Out': task.info['output'].encode('utf-8').strip(),
                              'description': description,
                              'returncode': return_code}
        except:
            result_obj = {'Status': "CELERY_FAILURE"}

    return jsonify(result_obj)


@deploy.route('/deploy-module-history')
@login_required
def deploy_module_history():
    return render_template('deploy/deploy_history.html')


@deploy.route('/jenkins-building')
@login_required
def jenkins_building():
    form = JenkinsExecForm()
    return render_template('deploy/jenkins_building.html', form=form)


@deploy.route('/jenkins-building-add', methods=['POST'])
@login_required
def jenkins_building_add():
    form = JenkinsExecForm()
    if form.validate_on_submit():
        job_name = form.job_name.data
        tag = form.tag.data
        job_type = form.job_type.data
        building_number = job_build(job_name=job_name, tag=tag, job_type=job_type)
        status_url = url_for('.jenkins_building_status', job_name=job_name, build_number=building_number, job_type=job_type)
        result = {'r': 0, 'job_name':job_name, 'tag':tag, 'building_number':building_number,
                  'Location': status_url}
    else:
        result = {'r': 1, 'error': form.errors}
    return jsonify(result)


@deploy.route('/jenkins-building-status')
@login_required
def jenkins_building_status():
    job_name = request.args.get('job_name')
    build_number = request.args.get('build_number')
    job_type = request.args.get('job_type')
    if job_name is None and build_number is None:
        return jsonify({"result": "ERROR",
                        "build_number": 0,
                        "out": "Please post job_name and build_number",
                        'building': 'false'})
    re = get_job_build_status(job_name, int(build_number), job_type)
    return jsonify(re)


@deploy.route('/jenkins-job-number')
@login_required
def jenkins_job_number():
    job_name = request.args.get('job_name')
    if job_name:
        return jsonify({"job_number": job_get_number(job_name), "server_list": get_inventory_hosts(job_name)})
    else:
        return jsonify({"job_number": '', "server_list": ''})


@deploy.route('/svn-tags')
@login_required
def svn_tags():
    job_name = request.args.get('job_name')
    if job_name:
        svn_url = job_get_svn(job_name)
        if svn_url['tag_dir']:
            svn_tag = svn_tag_list(url=svn_url['tag_dir'], tags_filter=svn_url['tags_filter'])
        else:
            svn_tag = {}
        return jsonify(svn_tag)
    else:
        return jsonify({})


@deploy.route('/tags-info')
@login_required
def tags_info():
    job_name = request.args.get('job_name')
    if job_name:
        repo_info = get_repo_info(job_name)
        if repo_info['job_type'] == 'svn' and repo_info['tag_dir']:
            # tag_info = svn_tag_list(url=repo_info['tag_dir'], tags_filter=repo_info['tags_filter'])
            tag_info = {'job_type': 'svn', 'tags': svn_tag_list(url=repo_info['tag_dir'], tags_filter=repo_info['tags_filter'])}
        elif repo_info['job_type'] == 'git':
            # tag_info = gitlab_tag_list(url=repo_info['git_url'])
            tag_info = {'job_type': 'git', 'tags': gitlab_tag_list(url=repo_info['git_url'])}
        else:
            tag_info = {}
        return jsonify(tag_info)
    else:
        return jsonify({})


@deploy.route('/flower-list')
@login_required
def flower_list():
    task_id = request.args.get('task_id')
    if task_id:
        tasks_api = Config.FLOWER_URL + 'api/task/info/' + task_id
        request_url = urllib2.Request(tasks_api)
        base64string = base64.encodestring('%s:%s' % (Config.FLOWER_USER, Config.FLOWER_PASSWORD)).replace('\n', '')
        request_url.add_header("Authorization", "Basic %s" % base64string)
        response = urllib2.urlopen(request_url)
        data = str(response.read().decode('utf-8')).replace('\'', '"')
        results = json.loads(data)
        if results['name'] != 'app.celery_runner.deploy_running_task':
            results = {}
    else:
        tasks_api = Config.FLOWER_URL + 'api/tasks'
        request_url = urllib2.Request(tasks_api)
        base64string = base64.encodestring('%s:%s' % (Config.FLOWER_USER, Config.FLOWER_PASSWORD)).replace('\n', '')
        request_url.add_header("Authorization", "Basic %s" % base64string)
        response = urllib2.urlopen(request_url)
        data = response.read().decode('utf-8')
        values = json.loads(data)
        results = []
        for key, value in values.iteritems():
            if value['name'] != 'app.celery_runner.deploy_running_task':
                continue
            uuid = value['uuid']
            args = value['args'][3:-2]
            if value['result']:
                result = json.loads(str(value['result']).replace('\\\'', '').replace('\"', '^').replace('\'', '"')
                                    .replace('\\x1b', '').replace('\\n', '<br />').replace('\\', '')
                                    .replace('[1;31;40m', '<font color=red>').replace('[1;32;40m', '<font color=green>')
                                    .replace('[0m', '</font>'))
            else:
                result = ''
            timestamp = datetime.fromtimestamp(value['timestamp']).strftime('%Y-%m-%d %H:%M:%S')
            state = value['state']
            results.append({
                'uuid': uuid,
                'args': args,
                'name': args.split()[2],
                'deploy_dir': args.split()[4],
                'build_number': args.split()[6],
                'result': result,
                'timestamp': timestamp,
                'state': state
            })
        # results = [{'args': value['args'][3:-2], 'result': json.loads(str(value['result']).replace('\'', '"')),
        #            'timestamp': datetime.fromtimestamp(value['timestamp']).strftime('%Y-%m-%d %H:%M:%S'),
        #            'state': value['state'], 'uuid': value['uuid']}
        #           for key, value in values.iteritems() if value['name'] == 'app.celery_runner.deploy_running_task']
    return jsonify(results)

app/templates/deploy/deploy_history.html
{% extends "base.html" %}

{% block title %}{{ config['SITE_NAME'] }} - Deploy History{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap-table-1.11.1/bootstrap-table.min.css') }}">
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Deploy History</h2>
</div>

<table id="ListTable"
       data-toggle="table"
       data-url="{{ url_for('deploy.flower_list') }}"
       data-method	="get"
       data-query-params=""
       data-pagination="true"
       data-page-size=10
       data-page-list="[10, 25, 50, All]"
       data-search="true"
       data-sort-name="timestamp"
       data-sort-order="desc"
       data-show-refresh="true"
       data-show-toggle="true"
       data-show-columns="true"
       data-show-export="true"
       data-export-data-type="selected"
       data-show-pagination-switch="true"
       data-striped="true"
       data-toolbar="#toolbar">
    <thead>
        <tr>
            <th data-field="uuid" data-sortable="false" data-switchable="false" data-visible="false">UUID</th>
            <th data-field="name" data-sortable="true">module</th>
            <th data-field="deploy_dir" data-sortable="false">deploy_dir</th>
            <th data-field="build_number" data-sortable="false">build_number</th>
            <th data-field="timestamp" data-sortable="true">Time</th>
            <th data-field="state" data-sortable="false" data-visible="false">State</th>
            <th data-field="result.output" data-sortable="true">Result</th>
        </tr>
    </thead>
</table>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='bootstrap-table-1.11.1/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap-table-1.11.1/locale/bootstrap-table-zh-CN.min.js') }}"></script>
<script>
$(function () {
    $('#ListTable').bootstrapTable({
    });
});
</script>
{% endblock %}

app/templates/deploy/deploy_module.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block title %}{{ config['SITE_NAME'] }} - Deploy Module{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Deploy Module</h2>
</div>

<div class="col-md-10">
    <form id="deploy_add" action="{{ url_for('deploy.deploy_module_add') }}" method="POST">
        {{ add_deploy_form.csrf_token }}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="control-label col-md-2" for="select_module">{{ add_deploy_form.module.label }}：</label>
                    <div class="col-md-4">
                        {{ add_deploy_form.module(class="form-control") }}
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="form-group">
                    <label class="col-md-2 control-label" for="version">{{ add_deploy_form.version.label }}：</label>
                    <div class="col-md-4">
                        <select class="form-control" id="version" name="version">
                            <option value="0">Choose...</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="col-md-2 control-label" for="deploy_dir">Select Deploy DIR:</label>
                    <div class="col-md-4">
                        <label class="checkbox-inline" for="apps">
                            <input type="checkbox" name="deploy_dir" value="apps" checked="checked">
                            apps
                        </label>

                        <label class="checkbox-inline" for="lib">
                            <input type="checkbox" name="deploy_dir" value="lib" checked="checked">
                            lib
                        </label>

                        <!-- <label class="checkbox-inline" for="config">
                            <input type="checkbox" name="deploy_dir" value="config">
                            config
                        </label> -->
                  </div>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="form-group">
                <label class="control-label col-md-2" for="deploy_server">Deploy Server：</label>
                <div id="deploy_server" class="col-md-4">
                    <p class="text-primary">&nbsp;&nbsp;&nbsp;&nbsp;</p>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-8">
                <button type="submit" class="btn btn-primary">submit</button>&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="reset" class="btn btn-danger">reset</button>
            </div>
        </div>
    </form>
</div>

<div class="col-md-12">
    <hr />
</div>

<div class="col-md-12">
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <p id="result"></p>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
function start_deploy_task() {
    var url = "{{ url_for('deploy.deploy_module_add') }}";
    var csrf_token = $('#csrf_token').val();
    var module = $('#module').val();
    var version = $('#version').val();
    var deploy_dir = [];
    $('input:checkbox[name=deploy_dir]:checked').each(function(){
        deploy_dir.push($(this).val());
    });

    // send ajax POST request to start background job
    $.ajax({
        type: 'POST',
        data: {'csrf_token':csrf_token, 'module':module , 'deploy_dir':deploy_dir, 'version': version},
        url: url,
        success: function(data, status, request) {
            if (data['r']==0){
                status_url = data['Location'];
                console.log("status_url: " + status_url);
                update_progress(status_url);
            }else{
                alert(data['error']);
                console.log(data['error']);
            }
        },
        error: function() {
            alert('Unexpected error');
        }
    });
}

function update_progress(status_url) {
    // send GET request to status URL
    $.getJSON(status_url, function(data) {
        var module_name = $('#module').val();
        var version = $('#version').val();
        var deploy_dir = [];
        $('input:checkbox[name=deploy_dir]:checked').each(function(){
            deploy_dir.push($(this).val());
        });

        // update UI
        $(':input[type="submit"]').prop('disabled', true);
        $(':input[type="reset"]').prop('disabled', true);
        $('#result').empty();
        $('#result').append("<img src=\"/static/images/loading.gif\" /><span class=\"text-warning\"><strong>" + module_name + "</strong> is Deploying...</sparn>");
        console.log(data['Status']);
        if (data['Status'] != 'PENDING' && data['Status'] != 'PROGRESS') {
            html = "<p class=\"text-primary\">Module: <strong>" + module_name + "</strong></p>" +
                "<p class=\"text-primary\">Version: <strong>" + version + "</strong></p>" +
                "<p class=\"text-primary\">Deploy_dir: <strong>" + deploy_dir + "</strong></p>" +
                "<p class=\"bg-primary text-warning\">Result: </p>";
            html = '';

            if (data['Status'] == 'SUCCESS') {
                // show result
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong>Deploy is ' + data['Status'] + '</strong></p><p>' + data['Out'].replace(/\n/g, '<br />') + '</p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
                $(':input[type="reset"]').prop('disabled', false);
            }else if(data['Status'] == 'CELERY_FAILURE'){
                // something unexpected happened
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong><strong>Deploy is ' + data['Status'] +  '.</strong></p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
                $(':input[type="reset"]').prop('disabled', false);
            } else {
                // something unexpected happened
                $('#result').empty();
                result = html + '<p class=\"text-primary\"><strong>Deploy is ' + data['Status'] +  '</strong></p><p>' +  data['Out'].replace(/\n/g, '<br />') + '</p>';
                $('#result').append(result);
                $(':input[type="submit"]').prop('disabled', false);
                $(':input[type="reset"]').prop('disabled', false);
            }
        } else {
            // rerun in 2 seconds
            setTimeout(function() {
                update_progress(status_url);
            }, 2000);
        }
    });
}

$(function() {
    $('#module').change(function() {
        if($('#module').val() == 0){
            $("#version").empty();
            $("#version").append("<option value=\"0\">Choose...</option>");
            return false;
        }
        var url = "{{ url_for('deploy.jenkins_job_number') }}?job_name=" + $('#module').val();
        $.get(url, function(result){
            $("#version").empty(); //clean select option
            for(var item in result['job_number']){
                $("#version").append("<option value=" + result['job_number'][item] + ">" + result['job_number'][item] + "</option>");
            }
            $('#deploy_server').empty(); //clean text
            $('#deploy_server').append("<p class=\"text-primary\">" + result['server_list'] + "</p>");
        });
    });

    $('#deploy_add').submit(function(event) {
        start_deploy_task();
        /*
        var url = "{{ url_for('deploy.deploy_module_add') }}";
        var csrf_token = $('#csrf_token').val();
        var module = $('#module').val();
        var version = $('#version').val();
        var deploy_dir = [];
        $('input:checkbox[name=deploy_dir]:checked').each(function(){
            deploy_dir.push($(this).val());
        });

        $.post(url,
            {'csrf_token':csrf_token, 'module':module , 'deploy_dir':deploy_dir, 'version': version},
            function (result){
            if(result["r"] == 0){

            }
            alert(result["r"]);
            alert(rsult["task_id"]);
        });
        */
        event.preventDefault();
    });
});
</script>
{% endblock %}

app/templates/deploy/jenkins_building.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field %}

{% block title %}{{ config['SITE_NAME'] }} - Jenkins Building{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Jenkins Building</h2>
</div>

<div class="col-md-12">
    <form id="jenkins_building" action="{{ url_for('deploy.jenkins_building') }}" method="POST">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label class="control-label col-md-1" for="select_module">{{ form.job_name.label }}：</label>
                    <div class="col-md-3">
                        {{ form.job_name(class="form-control") }}
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="form-group">
                    <label class="control-label col-md-1" for="tag">{{ form.tag.label }}：</label>
                    <div class="col-md-3">
                        <select class="form-control" id="tag" name="tag">
                            <option value="0">Choose...</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-4">
                <div class="form-group">
                    <label class="control-label" for="job_type">{{ form.job_type.label }}：</label>
                    <span id="job_type"></span>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <p></p>
        </div>

        <div class="form-group">
            <div class="col-sm-4">
            </div>
            <div class="col-sm-8">
                <button type="submit" class="btn btn-primary">submit</button>&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="reset" class="btn btn-danger">reset</button>
            </div>
        </div>
    </form>
</div>

<div class="col-md-12">
    <hr />
</div>

<div class="col-md-12">
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <p id="result"></p>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
function start_build_task() {
    var url = "{{ url_for('deploy.jenkins_building_add') }}";
    var csrf_token = $('#csrf_token').val();
    var job_name = $('#job_name').val();
    var tag = $('#tag').val();
    var job_type =$('#job_type').text();
    if (job_name == 0){
        alert("Please Select Exec Job.");
        return false;
    }

    // send ajax POST request to start background job
    $.ajax({
        type: 'POST',
        data: {'csrf_token':csrf_token, 'job_name':job_name , 'tag':tag, 'job_type': job_type},
        url: url,
        success: function(data, status, request) {
            if (data['r']==0){
                status_url = data['Location'];
                console.log("status_url: " + status_url);
                update_progress(status_url);
            }else{
                alert(data['error']);
                console.log(data['error']);
            }
        },
        error: function() {
            alert('Unexpected error');
        }
    });
}

function update_progress(status_url) {
    // send GET request to status URL
    $.getJSON(status_url, function(data) {
        var job_name = $('#job_name').val();
        var tag = $('#tag').val();
        var html = "";

        // update UI
        $(':input[type="submit"]').prop('disabled', true);
        $(':input[type="reset"]').prop('disabled', true);
        $('#result').empty();
        $('#result').append("<img src=\"/static/images/loading.gif\" /><span class=\"text-warning\"><strong>" + job_name + "</strong> is Building...</sparn>");
        console.log(data['result']);
        if (data['result'] == "PENDING" || data['result'] == null){
            // rerun in 2 seconds
            setTimeout(function() {
                update_progress(status_url);
            }, 2000);
        }else if ( data['result'] == 'SUCCESS' && data['building'] == false) {
            // show result
            $('#result').empty();
            var revisions = data['revisions'];
            var html2 = '';
            for (i in revisions) {
                html2 += "<p class=\"text-primary\">Repo INFO: <strong>" + revisions[i].module +
                    "</strong></p><p class=\"text-primary\">Version: <strong>" + revisions[i].revision + "</strong></p>";
            }
            var result = html + '<p class=\"text-primary\"><strong>Job is ' + job_name + '</strong></p>' +
                '<p class=\"text-primary\">TAG: <strong>' + tag + '</strong></p>' + html2 +
                '<p class="text-primary">Build_number: <strong>' + data['build_number'] + '</strong></p>';
            $('#result').append(result);
            $(':input[type="submit"]').prop('disabled', false);
            $(':input[type="reset"]').prop('disabled', false);
        }else if(data['result'] == 'ERROR'){
            // something unexpected happened
            $('#result').empty();
            var htm2 = '<hr /><p class=\"text-danger\"><strong>Building is ERROR!</strong></p>'
            result = html + '<p class=\"text-primary\"><strong><strong>Job is ' + job_name +  '</strong></p>' +
                '<p class=\"text-primary\">TAG: <strong>' + tag + '</strong></p>' + html2;
            $('#result').append(result);
            $(':input[type="submit"]').prop('disabled', false);
            $(':input[type="reset"]').prop('disabled', false);
        } else {
            // rerun in 2 seconds
            setTimeout(function() {
                update_progress(status_url);
            }, 2000);
        }
    });
}

$(function() {
    $('#job_name').change(function() {
        if($('#job_name').val() == 0){
            $("#tag").empty();
            $("#tag").append("<option value=\"0\">Choose...</option>");
            $("#job_type").empty();
            return false;
        }
        var url = "{{ url_for('deploy.tags_info') }}?job_name=" + $('#job_name').val();
        $.get(url, function(result){
            $("#job_type").text(result['job_type']);
            $("#tag").empty(); //clean select option
            for(var item in result['tags']){
                $("#tag").append("<option value=" + result['tags'][item] + ">" + result['tags'][item] + "</option>");
            }
        });
    });

    $("#jenkins_building").submit(function (event) {
        start_build_task();
        event.preventDefault();
    });
});
</script>
{% endblock %}